### ISSUE TITLE
Notification @SmilerV

### ISSUE THREAD

**Issue by Mabeeck2010** [SmilerV/Python-Tetris#1]
Ich habe vergessen, dich nach deiner Telefonnummer zu fragen.
Hast du Discord? Wenn ja, dann könntest du mich da Anrufen.

**Comment by SmilerV** [comment]
Nein Discord Username ist Smilervortex

Mabeeck2010 ***@***.***> schrieb am Fr., 19. Juli 2024, 16:31:

**Comment by Mabeeck2010** [comment]
Du kannst dises Issue jetzt löschen, indem du auf der rechten Seite die option löschen ganz unten auswählst. Das kannst nur du als Besitzer von diesem Repository.
